# Import Libraries and Create File Path

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
#pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
file = "datasets_1377_2482_Netflix Shows.csv"
df = pd.read_csv(file, encoding='latin-1')

In [3]:
df

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

## Drop unnecessary columns

In [4]:
df = df.drop(['ratingDescription','release year', 'user rating size'], axis=1)
df

,title,rating,ratingLevel,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82.0
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",NaN
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94.0
...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",97.0
996,The Secret Life of Pets,PG,for action and some rude humor,NaN
997,Precious Puppies,TV-G,Suitable for all ages.,NaN
998,Beary Tales,TV-G,Suitable for all ages.,NaN
999,Growing Up Wild,G,NaN,80.0

## Drop Null Values from "Title" and "Usering Rateing Score" columns

In [5]:
df.dropna(subset=['rating','user rating score'], inplace=True)
df

,title,rating,ratingLevel,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94.0
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95.0
...,...,...,...,...
986,PokÃŒÂ©mon: Indigo League,TV-Y,Suitable for all ages.,74.0
988,Paddington,PG,mild action and rude humor,70.0
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,72.0
995,The BFG,PG,"for action/peril, some scary moments and brief...",97.0
999,Growing Up Wild,G,NaN,80.0

## Rename the Columns

In [6]:
df = df.rename(columns={'title':'title','rating':'age_rating','ratingLevel':'rating_level','user rating score':'user_rating'})
df

,title,age_rating,rating_level,user_rating
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94.0
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95.0
...,...,...,...,...
986,PokÃŒÂ©mon: Indigo League,TV-Y,Suitable for all ages.,74.0
988,Paddington,PG,mild action and rude humor,70.0
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,72.0
995,The BFG,PG,"for action/peril, some scary moments and brief...",97.0
999,Growing Up Wild,G,NaN,80.0

## Replace Other Null Values with Empty String

In [7]:
df = df.replace(np.nan, '', regex=True)
df

,title,age_rating,rating_level,user_rating
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94.0
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95.0
...,...,...,...,...
986,PokÃŒÂ©mon: Indigo League,TV-Y,Suitable for all ages.,74.0
988,Paddington,PG,mild action and rude humor,70.0
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,72.0
995,The BFG,PG,"for action/peril, some scary moments and brief...",97.0
999,Growing Up Wild,G,,80.0

## Make Sure the Data Type of Each Column is Correct

In [9]:
df = df.astype({"title": str, "age_rating": str, "rating_level": str, "user_rating": int})
df

,title,age_rating,rating_level,user_rating
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95
...,...,...,...,...
986,PokÃŒÂ©mon: Indigo League,TV-Y,Suitable for all ages.,74
988,Paddington,PG,mild action and rude humor,70
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,72
995,The BFG,PG,"for action/peril, some scary moments and brief...",97
999,Growing Up Wild,G,,80

## Check for duplicates 'Titles' and double check the result

In [10]:
df[df.duplicated('title')]

,title,age_rating,rating_level,user_rating
52,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
53,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
56,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94
57,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95
58,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,97
...,...,...,...,...
986,PokÃŒÂ©mon: Indigo League,TV-Y,Suitable for all ages.,74
988,Paddington,PG,mild action and rude humor,70
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,72
995,The BFG,PG,"for action/peril, some scary moments and brief...",97
999,Growing Up Wild,G,,80

In [11]:
df.loc[df['title'] == 'Grey\'s Anatomy']

,title,age_rating,rating_level,user_rating
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
52,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
263,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
353,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
403,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
451,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98

In [12]:
df.loc[df['title'] == 'Prison Break']

,title,age_rating,rating_level,user_rating
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
53,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
264,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
311,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
355,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
405,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
454,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98

## Drop duplicates and reset index

In [13]:
df = df.drop_duplicates('title')
df.reset_index(drop=True, inplace=True)
df

,title,age_rating,rating_level,user_rating
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",82
1,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,98
2,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,98
3,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,94
4,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,95
...,...,...,...,...
249,Blank Check,PG,Parental guidance suggested. May not be suitab...,93
250,Heavyweights,PG,some rude language and pranks,74
251,D2: The Mighty Ducks,PG,some mild language and rough hockey action,70
252,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,80
253,H2O: Just Add Water,TV-PG,Parental guidance suggested. May not be suitab...,74

## Create database connection

In [14]:
connection_string = "postgres:postgres@localhost:5432/ETL_Project"
engine = create_engine(f'postgresql://{connection_string}',pool_size=10, max_overflow=20)

In [15]:
engine.table_names()

['netflix_rating']

## Load DataFrames into SQL database

In [16]:
df.to_sql(name='netflix_rating', con=engine, if_exists='append', index=False)